### ISSUE TITLE
DefunctConnection

### ISSUE THREAD

**Issue by mrazam110** [ChoadPet/NWListenerTest#1]
Hi @ChoadPet 

I hope you're doing well. I am working on a similar application and having Network implementation. 
```
failed(-65569: DefunctConnection)
failed(POSIXErrorCode: Address already in use) (till 25-30 seconds after Defunct)
then ready
```

iPhone 7 - iOS 13.5.1

Have you got something resolved? that might be helpful for me

Thanks in advance

**Comment by ChoadPet** [comment]
Hi @mrazam110!
We did change mobile app to client, and it just connect some host and port using `NWConnection`, so `NWListener` not used anymore and it's resolve the problem of address already in use.
